### ISSUE TITLE
Can you make it use a .scss-lint.yml file that's on another directory (not in the current open project)?

### ISSUE THREAD

**Issue by vivgui** [adamwalzer/vscode-scss-lint#10]

**Comment by donni106** [comment]
Do you think that it would be fine to define the directory in the plugin settings? 
I think there is no possibility to find the file automatically outside the project.

**Comment by vivgui** [comment]
YES, that's exactly what I need!

**Comment by adamwalzer** [comment]
The fix is in version `0.0.17`. Let me know if it doesn't work. Also, it'd be nice if our extension had some reviews 😄

**Comment by vivgui** [comment]
Hey @adamwalzer I just updated the extension and the scssLint.configDir option doesnt work. This is what I have on my settings.json file:

`"scssLint.configDir": "/Users/vivianguillen/.scss-lint.yml",`

I double checked that the path was correct but it isnt working, can you help me?

**Comment by adamwalzer** [comment]
@viviangb It should be just the directory. `"scssLint.configDir": "/Users/vivianguillen/",` Hope that works. Let me know.

**Comment by vivgui** [comment]
@adamwalzer yep that did it! Thank you! Also left you a review :)

**Comment by adamwalzer** [comment]
@viviangb thank you so much! Happy coding!
