### ISSUE TITLE
Doesn't show anything

### ISSUE THREAD

**Issue by marcelhadorn** [adamwalzer/vscode-scss-lint#15]
Can't make it to run, followed all the steps described, scss-lint in console works properly with the given .scss-lint.yml file.

**Comment by adamwalzer** [comment]
Hey @marcelhadorn,

Thanks for taking the time to file an issue. Can you tell me a little more about your setup? What version of scss_lint? Windows/Mac/Linux? Any user settings? Using css/scss? What command do you run in your console? What does the output look like in your console?

**Comment by marcelhadorn** [comment]
Sorry my issue was a bit uninformative. I'm on a MacPro with MacOS 10.13, I guess I was using the latest scss_lint (0.56.0) and using scss. I used `scss-lint`which output mi a list of Warnings and Errors throughout files in a folder. However, might it be that I'm not using the ruby sass but the libsass library to compile?

Meanwhile I've switched to sass-lint extension which runs with node sass-lint which works fine. However if it helps I can still run some tests for you.

**Comment by adamwalzer** [comment]
Well, it's up to you if you'd like to run tests. I'll happily try to debug if I have a bit more information, but if you'd rather not that's understandable as well. The most useful information would be what command do you run in the terminal? What output do you get? And what directory do you run the command in relative to your working directory?

**Comment by marcelhadorn** [comment]
I can run tests if you need me to, no rpblem. However if I'm the only one having that issue, maybe you can invest your time better. ;)

As i mentioned I run `scss-lint` command in the root of the working dir. Output is something like this:
```
…
sass/style.scss:279:1 [W] Indentation: Line should be indented with spaces, not tabs
sass/style.scss:283:1 [W] Indentation: Line should be indented with spaces, not tabs
sass/style.scss:284:21 [W] ColorVariable: Color literals like `#f1f1e9` should only be used in variable declarations; they should be referred to via variable everywhere else.
…
```

**Comment by adamwalzer** [comment]
Yeah. Seems like it should work to me. If anyone else has any insight on this issue or is also experiencing this issue please let me know or create a PR with a potential fix.

**Comment by adamwalzer** [comment]
A new version just got released. Since I can't reproduce your issue, it's hard for me to know, but I think it may resolve your issue. Let me know. Thanks!

**Comment by YavorIvanov** [comment]
Hey there. Strange issue here like this. I spent an hour or so between my iMac and Macbook Pro figuring out why on the Macbook it doesn't show anything while on the iMac it works perfect. Versions of sass are identical as is the scss-lint command. Any idea how to proceed with debugging this further?
Just to clarify all settings and packages are the same.

**Comment by YavorIvanov** [comment]
Hm this has been very strange. It seem rbenv has been an issue. 

Though on my Macbook it has been globally set and the version and pathing for rbenv are ok, it seems that it should always use the system ruby.

Might be worth taking a look though in the future.

**Comment by adamwalzer** [comment]
@YavorIvanov do you get the same response when you run scss-lint in the command line on both devices? This extension simply executes scss-lint in the terminal and parses the response to display the errors and warnings in vscode. If it's not working in the terminal, it won't work for this extension.
