### ISSUE TITLE
Missing fallback config file

### ISSUE THREAD

**Issue by explorador** [adamwalzer/vscode-scss-lint#18]
It gives an error when no config file is present and messes up the editor.

Something like this should fix it:
https://marketplace.visualstudio.com/items?itemName=glen-84.sass-lint
Configuration option #2.

**Comment by adamwalzer** [comment]
@explorador thanks for reporting this issue. I'll try to fix it sometime this week. Sorry for the wait, I just saw this issue.

**Comment by adamwalzer** [comment]
@explorador I adjusted the extension so if it doesn't find a config file, it just uses the default scss-lint configs now. Should be fixed in 0.1.2. Let me know if you see the fix working for you. I'll wait to hear from you before I close this issue.

**Comment by explorador** [comment]
Works! Thanks a lot!
