### ISSUE TITLE
Error running scss-lint: invalid option: --no-color

### ISSUE THREAD

**Issue by mazikwyry** [adamwalzer/vscode-scss-lint#19]
VS Code version 1.22.2 
scss-lint version 0.1.2
scss_lint gem version 0.49.0

Tried to install reinstall, clean up gems and I still get the same error. 
I have no idea where the `no-color` option is set.

![image](https://user-images.githubusercontent.com/1079965/38853567-fb0758ec-421d-11e8-8bcc-89e7d84c6e7e.png)

It may be useful information that I use `rvm`

Happy to help you with investigation.
Thanks in advance

**Comment by adamwalzer** [comment]
Thanks for reporting this issue. My apologies that I'm just seeing it now. I can hopefully look more into this this week or weekend. I'll let you know when I have a fix. To explain, I believe I have --no-color automatically set to make sure the color formatting doesn't interfere with the regex we use to parse the data the ruby gem returns to the extension. I'll see if possibly having the color would not be an issue. I'll let you know what I find when I look into it.

**Comment by adamwalzer** [comment]
@mazikwyry this issue should be fixed in version `0.1.3`. Please let me know if the issue still persists.

**Comment by adamwalzer** [comment]
Alright. I'm going to close this issue since it appears to be fixed on my end.
