### ISSUE TITLE
Doesn't respect `exclude` items

### ISSUE THREAD

**Issue by garyking** [adamwalzer/vscode-scss-lint#20]
I have `exclude` items in my `.scss-lint.yml`, and they are respected by `scss-lint` in the shell. But this extension doesn't respect these rules, and still shows warnings on files that should be excluded.

**Comment by adamwalzer** [comment]
@garyking thanks for submitting the issue. I will look into fixing this issue soon.

**Comment by adamwalzer** [comment]
I've been quite busy last week and this week. I'm not sure how soon I'll be able to get to this issue. If someone else wants to look into it, feel free to do so. If not, I'll hopefully get to it in the next couple of weeks.

**Comment by adamwalzer** [comment]
@garyking this issue should now be resolved in version 0.1.4 of the extension. Check it out and let me know if you're seeing it function properly. Thanks!

**Comment by adamwalzer** [comment]
Ok I'm going to assume this is resolved and close this issue

**Comment by amaisano** [comment]
I tried with both relative and absolute paths... no dice. Do you have an example of this setting/config you could please post? Thanks.

**Comment by adamwalzer** [comment]
@amaisano thank you for the comment. I'm at a wedding this weekend but maybe this other issue can help you with your question. https://github.com/adamwalzer/vscode-scss-lint/issues/10#issuecomment-317212079 and if that's helpful then please let me know I can update the readme to be more clear.

**Comment by amaisano** [comment]
Perfect - thanks! (Enjoy the wedding!)
