### ISSUE TITLE
CRLF line endings work, but LF does not

### ISSUE THREAD

**Issue by entozoon** [adamwalzer/vscode-scss-lint#23]
Hi there, sorry to be a pain again - I'm trying to improve coding standards at my workplace so this plugin is vital :)

Seems like a pretty clean cut bug, CRLF format is fine, but LF errors out. 

![lf](https://i.imgur.com/l5LU7a2.gif "crlf")

**Comment by entozoon** [comment]
Simple fix actually:
https://github.com/adamwalzer/vscode-scss-lint/pull/24

**Comment by adamwalzer** [comment]
No worries. I'm happy this extension is helping. I merged and deployed your fix.
