### ISSUE TITLE
`FinalNewLine` not marked

### ISSUE THREAD

**Issue by phc284** [adamwalzer/vscode-scss-lint#25]
Version: **0.1.7**

## Problem ##
`FinalNewLine` is not showing error when configured and no new line is added after ending scss style

**Comment by adamwalzer** [comment]
Hey @phc284,

Thanks for reporting the issue. I'll try to look into this soon. In the mean time, I'd like to make sure I understand the issue. Is `FinalNewLine` throwing an error when you run scss-lint in your terminal? Also, are you saying you expect the new line to automatically be added? This extension doesn't automatically fix any errors. It simply reports them back to you. You should use another extension to do that if you wish to do that.

Thanks,
Adam

**Comment by phc284** [comment]
It does throw an error when running scss-lint in the terminal and I am not expecting it to be auto-fixed. In my editor (VSCode) it does not show a warning or error that there should be a new line at the end of the `.scss` file

**Comment by adamwalzer** [comment]
This is actually an error in scss-lint. I will see if I can implement this here in the extension itself, otherwise I would have to submit a PR to scss-lint. I'll try to look into it in the next couple of days.

**Comment by adamwalzer** [comment]
@phc284 the issue should be resolved in version **0.1.8** let me know if you're still seeing problems. Thanks!

**Comment by phc284** [comment]
Working great! Thanks for the quick resolve! @adamwalzer
