### ISSUE TITLE
When a file is deleted, remove associated diagnostic object(s)

### ISSUE THREAD

**Issue by Seairth** [adamwalzer/vscode-scss-lint#38]
If a file has diagnostic objects associated to it when it is deleted, the diagnostic objects are not removed.  This causes the problems pane to display erroneous messages that cannot be cleared.

Ideally, when the workspace reports deleted files, the diagnostic collection is updated to remove the deleted files.

**Comment by adamwalzer** [comment]
I looked into this and it looks like it could be relatively easily accomplished using workspace.createFileSystemWatcher which returns a FileSystemWatcher which exposes onDidDelete. If you're interested, I'd happily review a PR. If now, I'm not sure when I would be able to get to this as you can probably tell by how long I took to respond here. As a workaround, you can always execute `Developer: Reload Window` after deleting files to refresh the scss problems.

Thanks!
