### ISSUE TITLE
Show warnings count in the bottom bar

### ISSUE THREAD

**Issue by donni106** [adamwalzer/vscode-scss-lint#4]
In #2 we came up with the idea to show a counter for warnings as well next to the errors.

@adamwalzer:
> The counter is displaying errors. Those were all warnings, not errors. Would we like to display warnings as well? I could adjust how that works.

I think that would be a good idea to have a counter for warnings as well. Maybe decidable per settings to show them in the bottom bar or not?
If showing errors and warnings together, the terms needs to be shorter.

**(icon) 0 scss-lint errors and 0 scss-lint warnings** is too much.
I think about something like **(icon) scss-lint 0 errors, 0 warnings** or only **(icon) 0 errors, 0 warnings** with a mouseover "scss-lint" if possible?

**Comment by yoodame** [comment]
This is a great idea!

I personally prefer less clutter so perhaps (icon) scss-lint (error icon) 0 (warning icon) 0. Similar to how vscode displays GitHub errors and warnings. Also, thoughts on making it clickable to the display the "problems" or "output" tabs?

**Comment by adamwalzer** [comment]
Ok I have updated the status bar to include warnings. I didn't make it clickable, but if you hover over the individual errors it should give you the message of what the error is. That to me does a better job of indicating the individual issues. If we feel this issue is closed, I will close it.

**Comment by donni106** [comment]
Thanks for the update: <img width="361" alt="bildschirmfoto 2017-05-29 um 13 58 57" src="https://cloud.githubusercontent.com/assets/1942953/26548986/06628824-4477-11e7-9675-38e52c9870f1.png">

I would also love to see the icons and counts fitting the git infos to the left, like @yoodame was suggesting:
> so perhaps (icon) scss-lint (error icon) 0 (warning icon) 0. Similar to how vscode displays GitHub errors and warnings

The error icon could also be the (x) like git is using?!

**Comment by adamwalzer** [comment]
Ok right now it's using the git Octicons. I'll have to see how to use other icons.

**Comment by donni106** [comment]
It doesn't have to be exactly the same. Maybe there is an (x) in the current available icon set?

**Comment by adamwalzer** [comment]
This will be part of the 0.0.15 update. I'm also making statusBarText an option so you can edit it to be whatever you want.

**Comment by adamwalzer** [comment]
These updates are out.

**Comment by donni106** [comment]
Thanks, after editing the option and restarting Code it worked perfectly.
