### ISSUE TITLE
Show errors and warnings in the problem tab?

### ISSUE THREAD

**Issue by donni106** [adamwalzer/vscode-scss-lint#5]
An useful enhancement could be the listing of errors and warnings in the problem tab of VS Code.

<img width="617" alt="bildschirmfoto 2017-05-29 um 14 03 39" src="https://cloud.githubusercontent.com/assets/1942953/26549165/ec5c22c2-4477-11e7-80eb-25441d11c37b.png">

Is that possible?
Is there a documentation how to do that?

**Comment by adamwalzer** [comment]
I think this is possible. I'll look into this, but so you know, if you hover over the error you can see the error text.

**Comment by donni106** [comment]
Yes I know.
If you find some documentation on how to add something in Code's problems tab, please link here.

**Comment by adamwalzer** [comment]
This should be resolved by https://github.com/adamwalzer/vscode-scss-lint/pull/9
