### ISSUE TITLE
Add possibility to underline code instead of background fill it

### ISSUE THREAD

**Issue by donni106** [adamwalzer/vscode-scss-lint#6]
Is it possible to add the option for underlining code? The background fill can be aggressive or frustrating to the developer. A minimized possibility could attract more users, especially if they can choose their favorite per settings.

**Comment by AndrewRayCode** [comment]
All other linting plugins I've used for VSCode (eslint, rubocop) and in any other editor use squiggly underlines. This plugin should do the same!

**Comment by adamwalzer** [comment]
I can add this as an option. I'll let you know when I do work on it. Thanks for the suggestion.

**Comment by adamwalzer** [comment]
This should be resolved by https://github.com/adamwalzer/vscode-scss-lint/pull/9
