### ISSUE TITLE
Shows linting errors in the wrong file

### ISSUE THREAD

**Issue by AndrewRayCode** [adamwalzer/vscode-scss-lint#8]
I have no idea how this is possible, but I have a scss file open in one tab, and to the right of it, a ruby file.

My scss file has linting errors. If I switch to the scss file tab, which apparently triggers the linting, then switch to the ruby file tab before linting completes, the errors are shown on the ruby file tab.

![screen shot 2017-06-05 at 2 44 11 pm](https://cloud.githubusercontent.com/assets/79215/26804633/7fecbaee-49fd-11e7-8e30-fa6d210c8d4a.png)

**Comment by adamwalzer** [comment]
I'll look into this one sometime soon.

**Comment by adamwalzer** [comment]
I am adding something to prevent this in 0.0.15, but it's hard for me to know if it works because I wasn't having the issue to begin with.

**Comment by adamwalzer** [comment]
This should be fixed. Let me know if it's still happening in 0.0.15. Thanks
